collisions delays, token collection, encapsulation
snake stops while eating block, acc to number on block, halfway through inc snake length on ball collection, moved reduce length on eating block code to a function, all tokens now being collected and removed from screen. 
Error: if duration between collection of tokens is less, latter token not being collected.